/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.pulgaslocas.gui;

import autonoma.pulgaslocas.elements.GestorJuego;
import autonoma.pulgaslocas.elements.GraphicContainer;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;

/**
 * 
 * @author Heily Yohana Rios Ayala <heilyy.riosa@gmail.com>
 * @since 20250430
 * @version 1.0.0
 * 
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    
    private GestorJuego gestor;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(GestorJuego gestor) {
        initComponents();

        this.setSize(900, 900);
         setResizable(false);
        this.setLocationRelativeTo(null);
        this.gestor = gestor;
        
          try{ 
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/PulgasLocas/images/JuegoIcono.png")).getImage());

            }catch(NullPointerException e){
                System.out.println("Imagen no encontrada");

            }

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnJuego = new javax.swing.JToggleButton();
        btnReiniciar = new javax.swing.JToggleButton();
        Portada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJuego.setBackground(new java.awt.Color(0, 204, 51));
        btnJuego.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnJuego.setText("Iniciar Juego");
        btnJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        btnReiniciar.setBackground(new java.awt.Color(204, 0, 0));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReiniciar.setText("Reiniciar Juego");
        jLayeredPane1.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        Portada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/pulgaslocas/images/Portada.png"))); // NOI18N
        jLayeredPane1.add(Portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoActionPerformed
       VentanaJuego  ventana= new VentanaJuego(this,true,gestor);
       ventana.setVisible(true);
    }//GEN-LAST:event_btnJuegoActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Portada;
    private javax.swing.JToggleButton btnJuego;
    private javax.swing.JToggleButton btnReiniciar;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
