/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.pulgaslocas.gui;

import autonoma.pulgaslocas.elements.CampoDeBatalla;
import autonoma.pulgaslocas.elements.GestorJuego;
import autonoma.pulgaslocas.elements.Puntaje;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Paz Puerta
 */
public class VentanaInformacionJuego extends javax.swing.JFrame {
    
    private GestorJuego gestor;
    private CampoDeBatalla campo;
     private String nomJugador;
    /**
     * Creates new form VentanaInformacionJuego
     */
    public VentanaInformacionJuego(VentanaPrincipal aThis, boolean par, GestorJuego gestor) {
        initComponents();

        this.setSize(900, 900);
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.gestor = gestor;
        
         pedirNombreJugador();
        
        try{ 
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/PulgasLocas/images/JuegoIcono.png")).getImage());

        }catch(NullPointerException e){
            System.out.println("Imagen no encontrada");

        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReiniciar1 = new javax.swing.JToggleButton();
        btnJugar1 = new javax.swing.JToggleButton();
        Jugador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JTextField();
        PuntajeJugador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 0, 22));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        btnReiniciar1.setBackground(new java.awt.Color(204, 0, 0));
        btnReiniciar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReiniciar1.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar1.setText("Reiniciar Juego");
        btnReiniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciar1MouseClicked(evt);
            }
        });

        btnJugar1.setBackground(new java.awt.Color(0, 153, 51));
        btnJugar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnJugar1.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar1.setText("Jugar");
        btnJugar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJugar1MouseClicked(evt);
            }
        });

        Jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/pulgaslocas/images/Jugador.jpeg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntaje");

        nombreJugador.setEditable(false);
        nombreJugador.setBackground(new java.awt.Color(255, 255, 255));

        PuntajeJugador.setEditable(false);
        PuntajeJugador.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReiniciar1)
                    .addComponent(btnJugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(PuntajeJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PuntajeJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Jugador))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnReiniciar1)
                        .addGap(85, 85, 85)
                        .addComponent(btnJugar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugar1MouseClicked
            if (nomJugador == null || nomJugador.isEmpty()) {
             PuntajeJugador.setText("Por favor ingresa un nombre.");
             return;
            }

         
         VentanaJuego ventana = new VentanaJuego(this, true, gestor);
         ventana.setVisible(true); 

         
         
         System.out.println(gestor.getPuntaje().getPuntajeMaximo());
         PuntajeJugador.setText(gestor.getPuntaje().getPuntajeActual()+ " ");
    }//GEN-LAST:event_btnJugar1MouseClicked

    private void btnReiniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciar1MouseClicked
        gestor.reiniciarJuego();
        PuntajeJugador.setText(gestor.getPuntaje().getPuntajeActual()+ " ");
    }//GEN-LAST:event_btnReiniciar1MouseClicked

     private void pedirNombreJugador() {
            while (true) {
            String nombre = JOptionPane.showInputDialog(this, "Ingresa tu nombre:");
            if (nombre != null && !nombre.trim().isEmpty()) {
                this.nomJugador = nombre.trim();
                nombreJugador.setText(nomJugador); 
                break;
            } else {
                JOptionPane.showMessageDialog(this, "Debes ingresar un nombre para continuar.");
            }
        }
    }

    public String getNombreJugador() {
        return nomJugador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jugador;
    private javax.swing.JTextField PuntajeJugador;
    private javax.swing.JToggleButton btnJugar1;
    private javax.swing.JToggleButton btnReiniciar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreJugador;
    // End of variables declaration//GEN-END:variables
}
